// Generated by scripts/sync-products.mjs. Do not edit.
// Source of truth is app/catalogue-data.ts; run `npm run sync:products` after
// changing it. Flat on purpose — see the note in the script for why admin does
// not import the catalogue directly.
export type CatalogueProduct = { slug: string; name: string; category: string };

export const catalogueProducts: CatalogueProduct[] = [
  {
    "slug": "3d",
    "name": "3D",
    "category": "Standard Roses"
  },
  {
    "slug": "absolut-in-pink",
    "name": "Absolut in Pink",
    "category": "Standard Roses"
  },
  {
    "slug": "amnesia",
    "name": "Amnesia",
    "category": "Standard Roses"
  },
  {
    "slug": "amsterdam",
    "name": "Amsterdam",
    "category": "Standard Roses"
  },
  {
    "slug": "andrea",
    "name": "Andrea",
    "category": "Standard Roses"
  },
  {
    "slug": "arctica",
    "name": "Arctica",
    "category": "Standard Roses"
  },
  {
    "slug": "barista",
    "name": "Barista",
    "category": "Standard Roses"
  },
  {
    "slug": "be-sweet",
    "name": "Be Sweet",
    "category": "Standard Roses"
  },
  {
    "slug": "bikini",
    "name": "Bikini",
    "category": "Standard Roses"
  },
  {
    "slug": "blush",
    "name": "Blush",
    "category": "Standard Roses"
  },
  {
    "slug": "born-free",
    "name": "Born Free",
    "category": "Standard Roses"
  },
  {
    "slug": "brighton",
    "name": "Brighton",
    "category": "Standard Roses"
  },
  {
    "slug": "cherry-brandy",
    "name": "Cherry Brandy",
    "category": "Standard Roses"
  },
  {
    "slug": "coffee-break",
    "name": "Coffee Break",
    "category": "Standard Roses"
  },
  {
    "slug": "cool-down",
    "name": "Cool Down",
    "category": "Standard Roses"
  },
  {
    "slug": "cool-water",
    "name": "Cool Water",
    "category": "Standard Roses"
  },
  {
    "slug": "deep-purple",
    "name": "Deep Purple",
    "category": "Standard Roses"
  },
  {
    "slug": "engagement",
    "name": "Engagement",
    "category": "Standard Roses"
  },
  {
    "slug": "escimo",
    "name": "Escimo",
    "category": "Standard Roses"
  },
  {
    "slug": "esperance",
    "name": "Esperance",
    "category": "Standard Roses"
  },
  {
    "slug": "explorer",
    "name": "Explorer",
    "category": "Standard Roses"
  },
  {
    "slug": "fair-lady",
    "name": "Fair Lady",
    "category": "Standard Roses"
  },
  {
    "slug": "faith",
    "name": "Faith",
    "category": "Standard Roses"
  },
  {
    "slug": "felicity",
    "name": "Felicity",
    "category": "Standard Roses"
  },
  {
    "slug": "freedom",
    "name": "Freedom",
    "category": "Standard Roses"
  },
  {
    "slug": "friendship",
    "name": "Friendship",
    "category": "Standard Roses"
  },
  {
    "slug": "frutetto",
    "name": "Frutetto",
    "category": "Standard Roses"
  },
  {
    "slug": "full-monty",
    "name": "Full Monty",
    "category": "Standard Roses"
  },
  {
    "slug": "glitz",
    "name": "Glitz",
    "category": "Standard Roses"
  },
  {
    "slug": "goldfinch",
    "name": "Goldfinch",
    "category": "Standard Roses"
  },
  {
    "slug": "gotcha",
    "name": "Gotcha",
    "category": "Standard Roses"
  },
  {
    "slug": "govinda",
    "name": "Govinda",
    "category": "Standard Roses"
  },
  {
    "slug": "green-romance",
    "name": "Green Romance",
    "category": "Standard Roses"
  },
  {
    "slug": "hermosa",
    "name": "Hermosa",
    "category": "Standard Roses"
  },
  {
    "slug": "high-and-candy",
    "name": "High & Candy",
    "category": "Standard Roses"
  },
  {
    "slug": "high-exotic",
    "name": "High & Exotic",
    "category": "Standard Roses"
  },
  {
    "slug": "high-and-magic",
    "name": "High & Magic",
    "category": "Standard Roses"
  },
  {
    "slug": "high-and-orange-magic",
    "name": "High & Orange Magic",
    "category": "Standard Roses"
  },
  {
    "slug": "high-and-yellow-magic",
    "name": "High & Yellow Magic",
    "category": "Standard Roses"
  },
  {
    "slug": "hot-lady",
    "name": "Hot Lady",
    "category": "Standard Roses"
  },
  {
    "slug": "hot-spot",
    "name": "Hot Spot",
    "category": "Standard Roses"
  },
  {
    "slug": "iguazu",
    "name": "Iguazu",
    "category": "Standard Roses"
  },
  {
    "slug": "jessica",
    "name": "Jessica",
    "category": "Standard Roses"
  },
  {
    "slug": "latina",
    "name": "Latina",
    "category": "Standard Roses"
  },
  {
    "slug": "lemonade",
    "name": "Lemonade",
    "category": "Standard Roses"
  },
  {
    "slug": "luciano",
    "name": "Luciano",
    "category": "Standard Roses"
  },
  {
    "slug": "malibu",
    "name": "Malibú",
    "category": "Standard Roses"
  },
  {
    "slug": "mandala",
    "name": "Mandala",
    "category": "Standard Roses"
  },
  {
    "slug": "mango-tango",
    "name": "Mango Tango",
    "category": "Standard Roses"
  },
  {
    "slug": "menta",
    "name": "Menta",
    "category": "Standard Roses"
  },
  {
    "slug": "momentum",
    "name": "Momentum",
    "category": "Standard Roses"
  },
  {
    "slug": "mondial",
    "name": "Mondial",
    "category": "Standard Roses"
  },
  {
    "slug": "moody-blue",
    "name": "Moody Blue",
    "category": "Standard Roses"
  },
  {
    "slug": "mother-of-pearl",
    "name": "Mother of Pearl",
    "category": "Standard Roses"
  },
  {
    "slug": "nena",
    "name": "Nena",
    "category": "Standard Roses"
  },
  {
    "slug": "nexus",
    "name": "Nexus",
    "category": "Standard Roses"
  },
  {
    "slug": "nina",
    "name": "Nina",
    "category": "Standard Roses"
  },
  {
    "slug": "novia",
    "name": "Novia",
    "category": "Standard Roses"
  },
  {
    "slug": "ocean-song",
    "name": "Ocean Song",
    "category": "Standard Roses"
  },
  {
    "slug": "orange-crush",
    "name": "Orange Crush",
    "category": "Standard Roses"
  },
  {
    "slug": "phoenix",
    "name": "Phoenix",
    "category": "Standard Roses"
  },
  {
    "slug": "pink-floyd",
    "name": "Pink Floyd",
    "category": "Standard Roses"
  },
  {
    "slug": "pink-mondial",
    "name": "Pink Mondial",
    "category": "Standard Roses"
  },
  {
    "slug": "playa-blanca",
    "name": "Playa Blanca",
    "category": "Standard Roses"
  },
  {
    "slug": "poma-rosa",
    "name": "Poma Rosa",
    "category": "Standard Roses"
  },
  {
    "slug": "proud",
    "name": "Proud",
    "category": "Standard Roses"
  },
  {
    "slug": "quicksand",
    "name": "Quicksand",
    "category": "Standard Roses"
  },
  {
    "slug": "redvolution",
    "name": "Redvolution",
    "category": "Standard Roses"
  },
  {
    "slug": "rosita-vendela",
    "name": "Rosita Vendela",
    "category": "Standard Roses"
  },
  {
    "slug": "secret-garden",
    "name": "Secret Garden",
    "category": "Standard Roses"
  },
  {
    "slug": "shocking-blue",
    "name": "Shocking Blue",
    "category": "Standard Roses"
  },
  {
    "slug": "silantoi",
    "name": "Silantoi",
    "category": "Standard Roses"
  },
  {
    "slug": "stardust",
    "name": "Stardust",
    "category": "Standard Roses"
  },
  {
    "slug": "sweet-akito",
    "name": "Sweet Akito",
    "category": "Standard Roses"
  },
  {
    "slug": "sweet-beat",
    "name": "Sweet Beat",
    "category": "Standard Roses"
  },
  {
    "slug": "sweet-cake",
    "name": "Sweet Cake",
    "category": "Standard Roses"
  },
  {
    "slug": "sweet-escimo",
    "name": "Sweet Escimo",
    "category": "Standard Roses"
  },
  {
    "slug": "sweet-lady",
    "name": "Sweet Lady",
    "category": "Standard Roses"
  },
  {
    "slug": "sweet-memory",
    "name": "Sweet Memory",
    "category": "Standard Roses"
  },
  {
    "slug": "sweet-unique",
    "name": "Sweet Unique",
    "category": "Standard Roses"
  },
  {
    "slug": "sweetness",
    "name": "Sweetness",
    "category": "Standard Roses"
  },
  {
    "slug": "tibet",
    "name": "Tibet",
    "category": "Standard Roses"
  },
  {
    "slug": "tiffany",
    "name": "Tiffany",
    "category": "Standard Roses"
  },
  {
    "slug": "toffee",
    "name": "Toffee",
    "category": "Standard Roses"
  },
  {
    "slug": "vi-pink",
    "name": "V.I. Pink",
    "category": "Standard Roses"
  },
  {
    "slug": "vendela",
    "name": "Vendela",
    "category": "Standard Roses"
  },
  {
    "slug": "all-4-love",
    "name": "All 4 Love",
    "category": "Garden Roses"
  },
  {
    "slug": "aloha",
    "name": "Aloha",
    "category": "Garden Roses"
  },
  {
    "slug": "antonia-gardens",
    "name": "Antonia Gardens",
    "category": "Garden Roses"
  },
  {
    "slug": "arya",
    "name": "Arya",
    "category": "Garden Roses"
  },
  {
    "slug": "aurora-gardens",
    "name": "Aurora Gardens",
    "category": "Garden Roses"
  },
  {
    "slug": "candlelight",
    "name": "Candlelight",
    "category": "Garden Roses"
  },
  {
    "slug": "candy-x-pression",
    "name": "Candy X-pression",
    "category": "Garden Roses"
  },
  {
    "slug": "cotton-x-pression",
    "name": "Cotton X-pression",
    "category": "Garden Roses"
  },
  {
    "slug": "country-blues",
    "name": "Country Blues",
    "category": "Garden Roses"
  },
  {
    "slug": "country-candy",
    "name": "Country Candy",
    "category": "Garden Roses"
  },
  {
    "slug": "country-home",
    "name": "Country Home",
    "category": "Garden Roses"
  },
  {
    "slug": "cream-x-pression",
    "name": "Cream X-pression",
    "category": "Garden Roses"
  },
  {
    "slug": "creamy-kiss",
    "name": "Creamy Kiss",
    "category": "Garden Roses"
  },
  {
    "slug": "dark-x-pression",
    "name": "Dark X-pression",
    "category": "Garden Roses"
  },
  {
    "slug": "dragonfly",
    "name": "Dragonfly",
    "category": "Garden Roses"
  },
  {
    "slug": "exotix-berry",
    "name": "Exotix Berry",
    "category": "Garden Roses"
  },
  {
    "slug": "free-spirit",
    "name": "Free Spirit",
    "category": "Garden Roses"
  },
  {
    "slug": "garden-spirit",
    "name": "Garden Spirit",
    "category": "Garden Roses"
  },
  {
    "slug": "hearts",
    "name": "Hearts",
    "category": "Garden Roses"
  },
  {
    "slug": "juicy-x-pression",
    "name": "Juicy X-pression",
    "category": "Garden Roses"
  },
  {
    "slug": "kahala",
    "name": "Kahala",
    "category": "Garden Roses"
  },
  {
    "slug": "mademoiselle",
    "name": "Mademoiselle",
    "category": "Garden Roses"
  },
  {
    "slug": "mandarin-x-pression",
    "name": "Mandarin X-pression",
    "category": "Garden Roses"
  },
  {
    "slug": "mayra-bridal-pink",
    "name": "Mayra Bridal Pink",
    "category": "Garden Roses"
  },
  {
    "slug": "mayra-hot-pink",
    "name": "Mayra Hot Pink",
    "category": "Garden Roses"
  },
  {
    "slug": "mayra-peach",
    "name": "Mayra Peach",
    "category": "Garden Roses"
  },
  {
    "slug": "mayra-pink",
    "name": "Mayra Pink",
    "category": "Garden Roses"
  },
  {
    "slug": "mayra-red",
    "name": "Mayra Red",
    "category": "Garden Roses"
  },
  {
    "slug": "mayra-white",
    "name": "Mayra White",
    "category": "Garden Roses"
  },
  {
    "slug": "melon-x-pression",
    "name": "Melon X-pression",
    "category": "Garden Roses"
  },
  {
    "slug": "pink-ohara",
    "name": "Pink O'Hara",
    "category": "Garden Roses"
  },
  {
    "slug": "pink-x-pression",
    "name": "Pink X-pression",
    "category": "Garden Roses"
  },
  {
    "slug": "queens-crown",
    "name": "Queen's Crown",
    "category": "Garden Roses"
  },
  {
    "slug": "shimmer",
    "name": "Shimmer",
    "category": "Garden Roses"
  },
  {
    "slug": "vicky-gardens",
    "name": "Vicky Gardens",
    "category": "Garden Roses"
  },
  {
    "slug": "white-ohara",
    "name": "White O'Hara",
    "category": "Garden Roses"
  },
  {
    "slug": "champagne",
    "name": "Champagne",
    "category": "Spray Roses"
  },
  {
    "slug": "champagne-majolika",
    "name": "Champagne Majolika",
    "category": "Spray Roses"
  },
  {
    "slug": "cream-majolika",
    "name": "Cream Majolika",
    "category": "Spray Roses"
  },
  {
    "slug": "elba",
    "name": "Elba",
    "category": "Spray Roses"
  },
  {
    "slug": "fibonacci",
    "name": "Fibonacci",
    "category": "Spray Roses"
  },
  {
    "slug": "fire-up",
    "name": "Fire Up",
    "category": "Spray Roses"
  },
  {
    "slug": "golden-blossom",
    "name": "Golden Blossom",
    "category": "Spray Roses"
  },
  {
    "slug": "morning-star",
    "name": "Morning Star",
    "category": "Spray Roses"
  },
  {
    "slug": "pink-majolika",
    "name": "Pink Majolika",
    "category": "Spray Roses"
  },
  {
    "slug": "portrait",
    "name": "Portrait",
    "category": "Spray Roses"
  },
  {
    "slug": "rubicon",
    "name": "Rubicon",
    "category": "Spray Roses"
  },
  {
    "slug": "shining-star",
    "name": "Shining Star",
    "category": "Spray Roses"
  },
  {
    "slug": "snowflake",
    "name": "Snowflake",
    "category": "Spray Roses"
  },
  {
    "slug": "star-blush",
    "name": "Star Blush",
    "category": "Spray Roses"
  },
  {
    "slug": "suspiro",
    "name": "Suspiro",
    "category": "Spray Roses"
  },
  {
    "slug": "sweet-dreams",
    "name": "Sweet Dreams",
    "category": "Spray Roses"
  },
  {
    "slug": "white-majolika",
    "name": "White Majolika",
    "category": "Spray Roses"
  },
  {
    "slug": "black-dragon",
    "name": "Black Dragon",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "candy-cane",
    "name": "Candy Cane Cocktail",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "dark-blue",
    "name": "Dark Blue",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "fall-hellujah",
    "name": "Fall Hellujah",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "fall-in-love",
    "name": "Fall in Love",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "fluffy",
    "name": "Fluffy",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "hallow-queen",
    "name": "Hallow Queen",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "harvest-delight",
    "name": "Harvest Delight",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "hopper",
    "name": "Hopper",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "light-blue",
    "name": "Light Blue",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "peeps",
    "name": "Peeps",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "pumpkin-patch",
    "name": "Pumpkin Patch",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "rainbow",
    "name": "Rainbow",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "santas-helper",
    "name": "Santa's Helper",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "spooktacular",
    "name": "Spooktacular",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "stalk-the-sun",
    "name": "Stalk The Sun",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "t-marshmellow",
    "name": "T-Marshmellow",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "x-mas-gift",
    "name": "X-mas Gift",
    "category": "Tinted/Dyed Roses"
  },
  {
    "slug": "mini-carnation",
    "name": "Mini Carnation",
    "category": "Carnations"
  },
  {
    "slug": "select-grade-carnation",
    "name": "Select-grade Carnation",
    "category": "Carnations"
  },
  {
    "slug": "asiatic-lily",
    "name": "Asiatic Lily",
    "category": "Lilies and Callas"
  },
  {
    "slug": "calla-lilies",
    "name": "Calla Lilies",
    "category": "Lilies and Callas"
  },
  {
    "slug": "hybrid-lilies",
    "name": "Hybrid Lilies",
    "category": "Lilies and Callas"
  },
  {
    "slug": "mini-calla-lilies",
    "name": "Mini Calla Lilies",
    "category": "Lilies and Callas"
  },
  {
    "slug": "oriental-lily",
    "name": "Oriental Lily",
    "category": "Lilies and Callas"
  },
  {
    "slug": "premium-lilies",
    "name": "Premium Lilies",
    "category": "Lilies and Callas"
  },
  {
    "slug": "bird-of-paradise",
    "name": "Bird of Paradise",
    "category": "Orchids and Tropicals"
  },
  {
    "slug": "cymbidium-orchid",
    "name": "Cymbidium Orchid",
    "category": "Orchids and Tropicals"
  },
  {
    "slug": "dendrobium",
    "name": "Dendrobium",
    "category": "Orchids and Tropicals"
  },
  {
    "slug": "phalaenopsis",
    "name": "Phalaenopsis (Moth Orchid)",
    "category": "Orchids and Tropicals"
  },
  {
    "slug": "alstroemeria",
    "name": "Alstroemeria",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "anemone",
    "name": "Anemone",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "butterfly-ranunculus",
    "name": "Butterfly Ranunculus",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "chrysanthemum",
    "name": "Chrysanthemum",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "daisy",
    "name": "Daisy",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "delphinium",
    "name": "Delphinium",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "gerbera",
    "name": "Gerbera",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "lisianthus",
    "name": "Lisianthus",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "molucella",
    "name": "Molucella",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "peony",
    "name": "Peony",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "premium-hydrangea",
    "name": "Premium Hydrangea",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "ranunculus",
    "name": "Ranunculus",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "snapdragon",
    "name": "Snapdragon",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "spider-chrysanthemum",
    "name": "Spider Chrysanthemum",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "stock",
    "name": "Stock",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "sunflowers",
    "name": "Sunflowers",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "sweet-pea",
    "name": "Sweet Pea",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "tulips",
    "name": "Tulips",
    "category": "Seasonal and Specialty"
  },
  {
    "slug": "babys-breath",
    "name": "Baby's Breath",
    "category": "Greens and Filler"
  },
  {
    "slug": "chamomile",
    "name": "Chamomile",
    "category": "Greens and Filler"
  },
  {
    "slug": "eucalyptus",
    "name": "Eucalyptus",
    "category": "Greens and Filler"
  },
  {
    "slug": "hanging-amaranthus",
    "name": "Hanging Amaranthus",
    "category": "Greens and Filler"
  },
  {
    "slug": "israeli-ruscus",
    "name": "Israeli Ruscus",
    "category": "Greens and Filler"
  },
  {
    "slug": "lepidium",
    "name": "Lepidium",
    "category": "Greens and Filler"
  },
  {
    "slug": "limonium",
    "name": "Limonium",
    "category": "Greens and Filler"
  },
  {
    "slug": "queen-of-lace",
    "name": "Queen of Lace",
    "category": "Greens and Filler"
  },
  {
    "slug": "solidago",
    "name": "Solidago",
    "category": "Greens and Filler"
  },
  {
    "slug": "statice",
    "name": "Statice",
    "category": "Greens and Filler"
  },
  {
    "slug": "wax-flower",
    "name": "Wax Flower",
    "category": "Greens and Filler"
  },
  {
    "slug": "mixed-bouquet",
    "name": "Mixed Bouquet",
    "category": "Bouquets"
  },
  {
    "slug": "rose-bouquet",
    "name": "Rose Bouquet",
    "category": "Bouquets"
  },
  {
    "slug": "tropical-bouquet",
    "name": "Tropical Bouquet",
    "category": "Bouquets"
  }
];
